Loading Image for all Phase Analysis
ZGainsforth/StoichiometryFitter pull request #12
Opened 2023-05-24 23:00 UTC by michaelofengend

Mostly edited base.html file

2023-05-24 23:55 UTC, ZGainsforth requested changes
There is a bug when running, is the main problem.  Also requirements.txt needs to be updated.  The css and image look good, but I didn't get the program to run quite far enough to test them.  Getting closer!

2023-05-24 23:55 UTC, ZGainsforth commented on StoichWeb.py
> +from flask_session import Session
This breaks the code.  flask_session needs to be added to requirements.txt

2023-05-24 23:55 UTC, ZGainsforth commented on StoichWeb.py
> +from flask_socketio import SocketIO
requirements.txt for flask_socketio

2023-05-24 23:55 UTC, ZGainsforth commented on StoichWeb.py
> +import eventlet
requirements.txt for eventlet

2023-05-24 23:55 UTC, ZGainsforth commented on StoichWeb.py
> +from flask_cors import CORS
requirements.txt for flask_cors

2023-05-24 23:55 UTC, ZGainsforth commented on StoichWeb.py
> +    app.run(app, debug=True)
<img width="622" alt="image" src="https://github.com/ZGainsforth/StoichiometryFitter/assets/6864619/0487c132-ca52-497e-9017-ca27e4f307f4">

2023-05-29 01:44 UTC, ZGainsforth approved these changes
Looking much better.  Still a couple bugs, but fewer than we started with.  :-)

2023-05-29 01:44 UTC, ZGainsforth commented on requirements.txt
> +json
json is built in and doesn't require pip install.

2023-05-29 01:44 UTC, ZGainsforth commented on ConfigData/phase GPT-4.py
Getting the error

`GPT-4 is not a model.`  

I think you need to use text-davinci-003 right now.  At least, I don't have access to GPT-4 in playground.  Maybe you do.  :-)  There should also be a way to enter in the model name along with a default that people are likely to have, and a quick explanation of what people need to do so people outside our team know how to enable it.  This can be fixed in a future bug fix.

2023-05-29 01:44 UTC, merged

2023-05-29 05:53 UTC, michaelofengend commented on ConfigData/phase GPT-4.py
Wouldn't using this model be better: gpt-3.5-turbo? Also I've linked a few screenshots for you in the slack. It feels as if GPT-4 is far superior than the rest. I highly recommend getting it's API or access.